# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://hyde.getpoole.com/
baseurl:          /

author:
  name:           'hyoon'
  url:            https://quasar-mars-030.notion.site/Heeyoon-Yang-d5eafbaba3c542589a0975a1e00b7091?pvs=4

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/yoony02
