# Site Settings
baseurl: ""
url : "https://yoony02.github.io"

# Blog Settings
theme_settings :
  title : Notes
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpg
    username : Heeyoon Yang
    description : Hi.
    experience :
      - start : 2021-08-02
        end : 
        experience : M.E., Artificial Intelligence, SKKU
      - start : 2016-03-02
        end : 2021-08-24
        experience : B.S., Library and Information Science, SKKU
      - start : 2019-09-01
        end : 2019-12-20
        experience : Exchange Student, SICE, Indiana University
    skills : 
      - skill : Recommendation Systems
        value : 70  # Percent value
      - skill : Session-based Recommendations
        value : 75  # Percent value
      - skill : Graph Neural Networks
        value : 60  # Percent value
        
  # Icons
  icons :
    email:  yoooyblooming@gmail.com
    linkedin:  # Full URL 
    github: yoony02
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
