# Site Settings
baseurl: ""
url : "https://yoony02.github.io"

# Blog Settings
theme_settings :
  title : Notes
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Heeyoon Yang
    description : Hi.
    experience :
      - start : 2016-03-02
        end : 2021-08-24
        experience : Library and Information Science, SKKU
    skills : 
      - skill : Recommendation Systems, Session-based Recommendations, Graph Neural Networks
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  yoooyblooming@gmail.com
    linkedin:  # Full URL 
    github: yoony02
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
